apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: ingress-demo-nginx
 spec:
   rules:
   - host: ingress.example.com
     http:
       paths:
       - path: /
         backend:
           serviceName: service-demo-nginx
           servicePort: 8090
