apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash
  labels:
    component: logstash
data:
  access-log.conf: |
    input {
      beats {
        port => "5044"
      }
      gelf {
        port => "12201"
        }
      }

      filter {
            kv {
              field_split => ","
        }
      }

    output {
      elasticsearch {
        hosts => [ "elasticsearch.elastic.svc.cluster.local:9200" ]
      }
    }
